/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penjualanmakanan;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class pemesanan extends javax.swing.JFrame {

    /**
     * Creates new form pemesanan
     */
    public pemesanan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        pilih1 = new javax.swing.JButton();
        pilih2 = new javax.swing.JButton();
        pilih3 = new javax.swing.JButton();
        pilih4 = new javax.swing.JButton();
        pilih8 = new javax.swing.JButton();
        pilih7 = new javax.swing.JButton();
        pilih6 = new javax.swing.JButton();
        pilih5 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        nama1 = new javax.swing.JTextField();
        nama2 = new javax.swing.JTextField();
        nama3 = new javax.swing.JTextField();
        nama4 = new javax.swing.JTextField();
        nama5 = new javax.swing.JTextField();
        harga1 = new javax.swing.JTextField();
        harga2 = new javax.swing.JTextField();
        harga3 = new javax.swing.JTextField();
        harga4 = new javax.swing.JTextField();
        harga5 = new javax.swing.JTextField();
        banyak1 = new javax.swing.JTextField();
        banyak2 = new javax.swing.JTextField();
        banyak3 = new javax.swing.JTextField();
        banyak4 = new javax.swing.JTextField();
        banyak5 = new javax.swing.JTextField();
        total1 = new javax.swing.JTextField();
        total2 = new javax.swing.JTextField();
        total3 = new javax.swing.JTextField();
        total4 = new javax.swing.JTextField();
        total5 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        transaksi = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        totalsemua = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        bayar = new javax.swing.JTextField();
        hitung = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        kembalian = new javax.swing.JTextField();
        orderpesanan = new javax.swing.JButton();
        ulang = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 0));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 153));
        jLabel1.setText("PEMESANAN NASI PADANG BOGOR");

        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("DAFTAR MAKANAN & MINUMAN");

        jLabel11.setText("Nasi");

        jLabel12.setText("Gulai Tunjang");

        jLabel13.setText("Ayam Pop");

        jLabel14.setText("Itiak Lado hijau");

        jLabel15.setText("Talua balado");

        jLabel16.setText("Es Teh");

        jLabel17.setText("Jus alpukat");

        jLabel18.setText("Rendang");

        pilih1.setText("Pilih");
        pilih1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilih1ActionPerformed(evt);
            }
        });

        pilih2.setText("Pilih");
        pilih2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilih2ActionPerformed(evt);
            }
        });

        pilih3.setText("Pilih");
        pilih3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilih3ActionPerformed(evt);
            }
        });

        pilih4.setText("Pilih");
        pilih4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilih4ActionPerformed(evt);
            }
        });

        pilih8.setText("Pilih");
        pilih8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilih8ActionPerformed(evt);
            }
        });

        pilih7.setText("Pilih");
        pilih7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilih7ActionPerformed(evt);
            }
        });

        pilih6.setText("Pilih");
        pilih6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilih6ActionPerformed(evt);
            }
        });

        pilih5.setText("Pilih");
        pilih5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilih5ActionPerformed(evt);
            }
        });

        nama1.setEditable(false);

        nama2.setEditable(false);

        nama3.setEditable(false);

        nama4.setEditable(false);

        nama5.setEditable(false);

        harga1.setEditable(false);
        harga1.setText("0");

        harga2.setEditable(false);
        harga2.setText("0");

        harga3.setEditable(false);
        harga3.setText("0");

        harga4.setEditable(false);
        harga4.setText("0");

        harga5.setEditable(false);
        harga5.setText("0");
        harga5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harga5ActionPerformed(evt);
            }
        });

        banyak1.setText("0");

        banyak2.setText("0");

        banyak3.setText("0");

        banyak4.setText("0");

        banyak5.setText("0");

        total1.setEditable(false);
        total1.setText("0");

        total2.setEditable(false);
        total2.setText("0");

        total3.setEditable(false);
        total3.setText("0");

        total4.setEditable(false);
        total4.setText("0");

        total5.setEditable(false);
        total5.setText("0");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel19.setText("Daftar Pesanan");

        jLabel20.setText("Nama");

        jLabel21.setText("Harga (RP)");

        jLabel22.setText("Banyaknya");

        jLabel23.setText("Total (RP)");

        transaksi.setText("Transaksi");
        transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksiActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Total");

        totalsemua.setEditable(false);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Bayar (Rp)");

        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("Kembalian");

        kembalian.setEditable(false);

        orderpesanan.setBackground(new java.awt.Color(0, 255, 0));
        orderpesanan.setText("Order Pesanan");
        orderpesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderpesananActionPerformed(evt);
            }
        });

        ulang.setText("Ulang");
        ulang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ulangActionPerformed(evt);
            }
        });

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nasi.png"))); // NOI18N

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/gulai tunjang.png"))); // NOI18N

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ayam pop.png"))); // NOI18N

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/itiak lado mudo.png"))); // NOI18N

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/taluabalado.png"))); // NOI18N

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/es teh.png"))); // NOI18N

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/jus alpukat.png"))); // NOI18N

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rendang.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel11)
                .addGap(251, 251, 251)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(194, 194, 194)
                .addComponent(jLabel14)
                .addGap(79, 79, 79))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nama5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nama4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nama3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nama2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nama1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(harga1)
                            .addComponent(harga2)
                            .addComponent(harga3)
                            .addComponent(harga4)
                            .addComponent(harga5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(banyak1)
                            .addComponent(banyak2)
                            .addComponent(banyak3)
                            .addComponent(banyak4)
                            .addComponent(banyak5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(total1)
                            .addComponent(total2)
                            .addComponent(total3)
                            .addComponent(total4)
                            .addComponent(total5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel20)
                        .addGap(69, 69, 69)
                        .addComponent(jLabel21)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel22)
                        .addGap(66, 66, 66)
                        .addComponent(jLabel23)))
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(totalsemua)
                    .addComponent(bayar)
                    .addComponent(transaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hitung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(orderpesanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ulang, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(447, 447, 447))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel15))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(pilih1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pilih5)
                                    .addComponent(jLabel31))))))
                .addGap(172, 172, 172)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel16)
                        .addComponent(pilih2))
                    .addComponent(jLabel32)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(pilih6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel29)
                                .addGap(31, 31, 31))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel33)
                                    .addComponent(pilih7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel30))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pilih3)
                                    .addComponent(jLabel17))
                                .addGap(207, 207, 207)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pilih4)
                                    .addComponent(jLabel18)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pilih8)
                                    .addComponent(jLabel34))
                                .addGap(8, 8, 8)))
                        .addGap(70, 70, 70))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(exit))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel29)))
                                .addGap(37, 37, 37))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(pilih1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pilih4)
                                    .addComponent(pilih3))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel16))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel17)
                                        .addComponent(jLabel18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(24, 24, 24)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel32)
                                                    .addComponent(jLabel31)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 12, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(pilih7)
                                                    .addComponent(pilih8)
                                                    .addComponent(pilih5)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(pilih6)
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel34))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pilih2))
                    .addComponent(jLabel27))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nama1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(harga1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(banyak1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(total1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nama2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(harga2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(banyak2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(total2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nama3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(harga3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(banyak3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(total3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nama4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(harga4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(banyak4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(total4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nama5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(harga5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(banyak5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(total5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(transaksi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel24)
                                    .addComponent(totalsemua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel25)
                                    .addComponent(bayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(orderpesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hitung)
                            .addComponent(ulang))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(47, 47, 47))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void pilih1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilih1ActionPerformed
        // TODO add your handling code here:
        if(nama1.getText().isEmpty()) {
            nama1.setText("Nasi");
            harga1.setText("8000");
        } else if(nama2.getText().isEmpty()) {
            nama2.setText("Nasi");
            harga2.setText("8000");
        } else if(nama3.getText().isEmpty()) {
            nama3.setText("Nasi");
            harga3.setText("8000");
        } else if(nama4.getText().isEmpty()) {
            nama4.setText("Nasi");
            harga4.setText("8000");
        } else if(nama5.getText().isEmpty()) {
            nama5.setText("Nasi");
            harga5.setText("8000");
        }
    }//GEN-LAST:event_pilih1ActionPerformed

    private void pilih2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilih2ActionPerformed
        // TODO add your handling code here:
        if(nama1.getText().isEmpty()) {
            nama1.setText("Gulai Tunjang");
            harga1.setText("25000");
        } else if(nama2.getText().isEmpty()) {
            nama2.setText("Gulai Tunjang");
            harga2.setText("25000");
        } else if(nama3.getText().isEmpty()) {
            nama3.setText("Gulai Tunjang");
            harga3.setText("25000");
        } else if(nama4.getText().isEmpty()) {
            nama4.setText("Gulai Tunjang");
            harga4.setText("25000");
        } else if(nama5.getText().isEmpty()) {
            nama5.setText("Gulai Tunjang");
            harga5.setText("25000");
        }
    }//GEN-LAST:event_pilih2ActionPerformed

    private void pilih3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilih3ActionPerformed
        // TODO add your handling code here:
        if(nama1.getText().isEmpty()) {
            nama1.setText("Ayam Pop");
            harga1.setText("25000");
        } else if(nama2.getText().isEmpty()) {
            nama2.setText("Ayam Pop");
            harga2.setText("25000");
        } else if(nama3.getText().isEmpty()) {
            nama3.setText("Ayam Pop");
            harga3.setText("25000");
        } else if(nama4.getText().isEmpty()) {
            nama4.setText("Ayam Pop");
            harga4.setText("25000");
        } else if(nama5.getText().isEmpty()) {
            nama5.setText("Ayam Pop");
            harga5.setText("25000");
        }
    }//GEN-LAST:event_pilih3ActionPerformed

    private void pilih4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilih4ActionPerformed
        // TODO add your handling code here:
        if(nama1.getText().isEmpty()) {
            nama1.setText("Itiak Lado hijau");
            harga1.setText("25000");
        } else if(nama2.getText().isEmpty()) {
            nama2.setText("Itiak Lado hijau");
            harga2.setText("25000");
        } else if(nama3.getText().isEmpty()) {
            nama3.setText("Itiak Lado hijau");
            harga3.setText("25000");
        } else if(nama4.getText().isEmpty()) {
            nama4.setText("Itiak Lado hijau");
            harga4.setText("25000");
        } else if(nama5.getText().isEmpty()) {
            nama5.setText("Itiak Lado hijau");
            harga5.setText("25000");
        }
    }//GEN-LAST:event_pilih4ActionPerformed

    private void pilih8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilih8ActionPerformed
        // TODO add your handling code here:
        if(nama1.getText().isEmpty()) {
            nama1.setText("Rendang");
            harga1.setText("55000");
        } else if(nama2.getText().isEmpty()) {
            nama2.setText("Rendang");
            harga2.setText("55000");
        } else if(nama3.getText().isEmpty()) {
            nama3.setText("Rendang");
            harga3.setText("55000");
        } else if(nama4.getText().isEmpty()) {
            nama4.setText("Rendang");
            harga4.setText("55000");
        } else if(nama5.getText().isEmpty()) {
            nama5.setText("Rendang");
            harga5.setText("55000");
        }
    }//GEN-LAST:event_pilih8ActionPerformed

    private void pilih7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilih7ActionPerformed
        // TODO add your handling code here:
        if(nama1.getText().isEmpty()) {
            nama1.setText("Jus alpukat");
            harga1.setText("10000");
        } else if(nama2.getText().isEmpty()) {
            nama2.setText("Jus alpukat");
            harga2.setText("10000");
        } else if(nama3.getText().isEmpty()) {
            nama3.setText("Jus alpukat");
            harga3.setText("10000");
        } else if(nama4.getText().isEmpty()) {
            nama4.setText("Jus alpukat");
            harga4.setText("10000");
        } else if(nama5.getText().isEmpty()) {
            nama5.setText("Jus alpukat");
            harga5.setText("10000");
        }
    }//GEN-LAST:event_pilih7ActionPerformed

    private void pilih6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilih6ActionPerformed
        // TODO add your handling code here:
        if(nama1.getText().isEmpty()) {
            nama1.setText("Es Teh");
            harga1.setText("8000");
        } else if(nama2.getText().isEmpty()) {
            nama2.setText("Es Teh");
            harga2.setText("8000");
        } else if(nama3.getText().isEmpty()) {
            nama3.setText("Es Teh");
            harga3.setText("8000");
        } else if(nama4.getText().isEmpty()) {
            nama4.setText("Es Teh");
            harga4.setText("8000");
        } else if(nama5.getText().isEmpty()) {
            nama5.setText("Es Teh");
            harga5.setText("8000");
        }
    }//GEN-LAST:event_pilih6ActionPerformed

    private void pilih5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilih5ActionPerformed
        // TODO add your handling code here:
        if(nama1.getText().isEmpty()) {
            nama1.setText("Talua balado");
            harga1.setText("12500");
        } else if(nama2.getText().isEmpty()) {
            nama2.setText("Talua balado");
            harga2.setText("12500");
        } else if(nama3.getText().isEmpty()) {
            nama3.setText("Talua balado");
            harga3.setText("12500");
        } else if(nama4.getText().isEmpty()) {
            nama4.setText("Talua balado");
            harga4.setText("12500");
        } else if(nama5.getText().isEmpty()) {
            nama5.setText("Talua balado");
            harga5.setText("12500");
        }
    }//GEN-LAST:event_pilih5ActionPerformed

    private void harga5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harga5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_harga5ActionPerformed

    private void transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksiActionPerformed
        // TODO add your handling code here:
        int row1 = Integer.parseInt(harga1.getText())*Integer.parseInt(banyak1.getText());
        int row2 = Integer.parseInt(harga2.getText())*Integer.parseInt(banyak2.getText());
        int row3 = Integer.parseInt(harga3.getText())*Integer.parseInt(banyak3.getText());
        int row4 = Integer.parseInt(harga4.getText())*Integer.parseInt(banyak4.getText());
        int row5 = Integer.parseInt(harga5.getText())*Integer.parseInt(banyak5.getText());
        total1.setText(""+row1);
        total2.setText(""+row2);
        total3.setText(""+row3);
        total4.setText(""+row4);
        total5.setText(""+row5);
        totalsemua.setText(""+(row1+row2+row3+row4+row5));
    }//GEN-LAST:event_transaksiActionPerformed

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // TODO add your handling code here:
        int uangKembalian = Integer.parseInt(bayar.getText())-Integer.parseInt(totalsemua.getText());
        kembalian.setText(""+uangKembalian);
    }//GEN-LAST:event_hitungActionPerformed

    private void orderpesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderpesananActionPerformed
        // TODO add your handling code here:
        if(totalsemua.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Harap Pesan Makanan atau Minuman Terlebih Dahulu");
        } else {
            int totalbelanja = Integer.parseInt(totalsemua.getText());
            new verifikasipelanggan(totalbelanja).setVisible(true);
        }
    }//GEN-LAST:event_orderpesananActionPerformed

    private void ulangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ulangActionPerformed
        // TODO add your handling code here:
        nama1.setText("");
        nama2.setText("");
        nama3.setText("");
        nama4.setText("");
        nama5.setText("");
        harga1.setText("0");
        harga2.setText("0");
        harga3.setText("0");
        harga4.setText("0");
        harga5.setText("0");
        banyak1.setText("0");
        banyak2.setText("0");
        banyak3.setText("0");
        banyak4.setText("0");
        banyak5.setText("0");
        total1.setText("0");
        total2.setText("0");
        total3.setText("0");
        total4.setText("0");
        total5.setText("0");
        totalsemua.setText("");
        bayar.setText("");
        kembalian.setText("");
    }//GEN-LAST:event_ulangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pemesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField banyak1;
    private javax.swing.JTextField banyak2;
    private javax.swing.JTextField banyak3;
    private javax.swing.JTextField banyak4;
    private javax.swing.JTextField banyak5;
    private javax.swing.JTextField bayar;
    private javax.swing.JButton exit;
    private javax.swing.JTextField harga1;
    private javax.swing.JTextField harga2;
    private javax.swing.JTextField harga3;
    private javax.swing.JTextField harga4;
    private javax.swing.JTextField harga5;
    private javax.swing.JButton hitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField kembalian;
    private javax.swing.JTextField nama1;
    private javax.swing.JTextField nama2;
    private javax.swing.JTextField nama3;
    private javax.swing.JTextField nama4;
    private javax.swing.JTextField nama5;
    private javax.swing.JButton orderpesanan;
    private javax.swing.JButton pilih1;
    private javax.swing.JButton pilih2;
    private javax.swing.JButton pilih3;
    private javax.swing.JButton pilih4;
    private javax.swing.JButton pilih5;
    private javax.swing.JButton pilih6;
    private javax.swing.JButton pilih7;
    private javax.swing.JButton pilih8;
    private javax.swing.JTextField total1;
    private javax.swing.JTextField total2;
    private javax.swing.JTextField total3;
    private javax.swing.JTextField total4;
    private javax.swing.JTextField total5;
    private javax.swing.JTextField totalsemua;
    private javax.swing.JButton transaksi;
    private javax.swing.JButton ulang;
    // End of variables declaration//GEN-END:variables
}
